# -*- coding: utf-8 -*-
"""OCR_Helper.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/121ydmw6OtFiIw58gFui9dN5D2GHQ03wl
"""

from tensorflow.keras.datasets import mnist
import numpy as np


def load_az_data(path):
    data = []
    labels = []

    for row in open(path):
        row = row.split(',')
        label = int(row[0])
        image = np.array([int(x) for x in row[1:]], dtype='uint8')
        image = image.reshape((28, 28))
        data.append(image)
        labels.append(label)
        data = np.array(data, dtype='float32')
        labels = np.array(labels, dtype='int')
        return (data, labels)


def load_mnist_data():
    ((trainData, trainLabels), (testData, testLabels)) = mnist.load_data()
    data = np.vstack([trainData, testData])
    labels = np.hstack([trainLabels, testLabels])
    return (data, labels)
